### ISSUE TITLE
How to choose a DNS server?

### ISSUE THREAD

**Issue by git-hub-learning** [ps100000/Blokada-VPN4Linux#5]
When the script asked me "What DNS do you want to use?" I just pressed Enter. Is this alright? If I want to use a certain DNS, should I just copy-paste the name from Blokada dashboard?

**Comment by git-hub-learning** [comment]
If I try to download Blokada config, copy DNS from there and paste into etc/wireguard/blokada.conf, the script fails (Something went wrong; the connection couldn't build up.)
If I paste just a name (like `Blokada Cloud`) it works, but www.dnsleaktest.com can detect my ip

**Comment by ps100000** [comment]
The idea is to enter the IP of the DNS server you want to use. Maybe should have been worded more clearly.
If you want to disable the VPN just run `sudo wg-quick down blokada` and to show the current state run `sudo wg show blokada`.
Tbh I'm not really active in the Blokada project anymore for a lot of reasons so don't expect any major updates to this repository. I hope this was helpful to you. 🙂

**Comment by git-hub-learning** [comment]
Thank you! :slightly_smiling_face: Could you please also tell how I can remove the script's cache? Because now it no longer asks for DNS and uses the cached one instead. Also when using the script or wireguard directly, my dns leaks when testing here: https://www.dnsleaktest.com. Do you have any suggestions on how this can be fixed?

**Comment by ps100000** [comment]
Just delete the config file in /etc/wireguard.

Nope. There could be a thousand different things going wrong there. Sorry.
